import { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ChevronDown } from 'lucide-react';
import { SectionHeading } from '../ui/SectionHeading';
import { cn } from '../../utils/cn';

const FAQS = [
  {
    q: 'Is my data stored anywhere?',
    a: 'No. Your assessment answers stay in your browser session and are sent only to the Gemini-powered analysis endpoint to generate your report. We do not persist your personal data on a server.',
  },
  {
    q: 'Do I need to create an account?',
    a: 'No account is required. You can run the assessment and download your PDF report immediately.',
  },
  {
    q: 'How accurate is the placement score?',
    a: 'The score is generated by Gemini using a structured rubric that weighs your skills, projects, CGPA, coding level, and communication. It is a guidance tool, not a guarantee, but it gives you a strong, honest baseline.',
  },
  {
    q: 'What if I do not have a resume yet?',
    a: 'The resume field is optional. You can paste a draft, a LinkedIn summary, or skip it entirely. The AI will still analyze everything else you provide.',
  },
  {
    q: 'Can I re-run the assessment after improving?',
    a: 'Absolutely. Revisit the assessment any time to update your skills and projects, then generate a fresh report to track your improvement.',
  },
  {
    q: 'Which roles does the agent support?',
    a: 'Software Developer, Backend Developer, Frontend Developer, Full Stack Developer, QA Engineer, Data Analyst, and AI Engineer. The roadmap adapts to whichever role you target.',
  },
];

export function FAQ() {
  const [open, setOpen] = useState<number | null>(0);

  return (
    <section id="faq" className="relative py-20 sm:py-28">
      <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
        <SectionHeading
          eyebrow="FAQ"
          title={<>Questions, answered</>}
          description="Everything you might want to know before running your first assessment."
        />

        <div className="mt-12 space-y-3">
          {FAQS.map((faq, i) => {
            const isOpen = open === i;
            return (
              <div
                key={faq.q}
                className={cn(
                  'card-surface overflow-hidden transition-all',
                  isOpen && 'shadow-card-hover border-brand-300/60 dark:border-brand-500/40',
                )}
              >
                <button
                  onClick={() => setOpen(isOpen ? null : i)}
                  className="flex w-full items-center justify-between gap-4 p-5 text-left"
                >
                  <span className="font-display text-base font-semibold text-slate-900 dark:text-white">{faq.q}</span>
                  <span
                    className={cn(
                      'flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-brand-50 dark:bg-brand-500/10 text-brand-600 dark:text-brand-300 transition-transform',
                      isOpen && 'rotate-180',
                    )}
                  >
                    <ChevronDown className="h-4 w-4" />
                  </span>
                </button>
                <AnimatePresence initial={false}>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.25 }}
                    >
                      <p className="px-5 pb-5 text-sm text-slate-600 dark:text-slate-300 leading-relaxed">{faq.a}</p>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
