import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Download, Home, RotateCcw, Share2 } from 'lucide-react';
import { Button } from '../components/ui/Button';
import { ScoreCircle } from '../components/ui/ScoreCircle';
import {
  BestRoleCard,
  CertificationsCard,
  FinalRecommendationCard,
  InterviewQuestionsCard,
  MissingSkillsCard,
  ProjectsCard,
  RoadmapCard,
  SkillGapCard,
  StrengthsCard,
  StudentSummary,
  TipsCard,
  WeaknessesCard,
} from '../components/dashboard/ReportSections';
import { SkillRadarChart } from '../components/dashboard/SkillRadarChart';
import { generatePlacementPdf } from '../utils/pdfGenerator';
import type { PlacementReport, StudentProfile } from '../types';

export function DashboardPage() {
  const navigate = useNavigate();
  const [report, setReport] = useState<PlacementReport | null>(null);
  const [profile, setProfile] = useState<StudentProfile | null>(null);
  const [downloading, setDownloading] = useState(false);

  useEffect(() => {
    const r = window.sessionStorage.getItem('placement-report');
    const p = window.sessionStorage.getItem('placement-profile');
    if (!r || !p) {
      navigate('/assessment');
      return;
    }
    try {
      setReport(JSON.parse(r));
      setProfile(JSON.parse(p));
    } catch {
      navigate('/assessment');
    }
  }, [navigate]);

  const stats = useMemo(() => {
    if (!report) return null;
    return {
      strengths: report.strengths.length,
      weaknesses: report.weaknesses.length,
      missing: report.missingSkills.length,
      companies: report.recommendedCompanies.length,
      roadmapItems: report.roadmap.length,
      projects: report.recommendedProjects.length,
    };
  }, [report]);

  if (!report || !profile || !stats) {
    return (
      <div className="min-h-screen flex items-center justify-center pt-24">
        <p className="text-sm text-slate-500 dark:text-slate-400">Loading your report...</p>
      </div>
    );
  }

  const handleDownload = () => {
    setDownloading(true);
    try {
      generatePlacementPdf(report, profile);
    } finally {
      setTimeout(() => setDownloading(false), 600);
    }
  };

  const handleShare = async () => {
    const text = `My Placement Readiness Score is ${report.placementScore}/100 (${report.status}). Best suited role: ${report.bestRole}. Generated by Placement Decision AI Agent.`;
    try {
      if (navigator.share) {
        await navigator.share({ title: 'My Placement Report', text });
      } else {
        await navigator.clipboard.writeText(text);
        alert('Report summary copied to clipboard.');
      }
    } catch {
      // user dismissed share - ignore
    }
  };

  return (
    <div className="relative min-h-screen pt-24 pb-16 bg-mesh-light dark:bg-mesh-dark">
      <div className="absolute inset-0 bg-grid [mask-image:radial-gradient(ellipse_at_top,black_30%,transparent_75%)]" />

      <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="flex flex-wrap items-end justify-between gap-4"
        >
          <div>
            <span className="section-eyebrow">Placement Report</span>
            <h1 className="mt-3 font-display text-3xl sm:text-4xl font-bold tracking-tight text-slate-900 dark:text-white">
              Your placement readiness, decoded
            </h1>
            <p className="mt-2 text-sm text-slate-500 dark:text-slate-400">
              Generated on {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            <Button variant="ghost" size="sm" onClick={() => navigate('/')} leftIcon={<Home className="h-4 w-4" />}>Home</Button>
            <Button variant="ghost" size="sm" onClick={() => navigate('/assessment')} leftIcon={<RotateCcw className="h-4 w-4" />}>Re-run</Button>
            <Button variant="ghost" size="sm" onClick={handleShare} leftIcon={<Share2 className="h-4 w-4" />}>Share</Button>
            <Button size="sm" onClick={handleDownload} loading={downloading} leftIcon={<Download className="h-4 w-4" />}>Download PDF</Button>
          </div>
        </motion.div>

        {/* Top section: score + summary */}
        <div className="mt-8 grid gap-6 lg:grid-cols-3">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="card-surface p-8 flex flex-col items-center justify-center"
          >
            <ScoreCircle score={report.placementScore} status={report.status} />
            <p className="mt-4 text-center text-sm text-slate-500 dark:text-slate-400 max-w-xs">
              Based on your skills, projects, CGPA, coding, and communication.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.15 }}
            className="lg:col-span-2"
          >
            <StudentSummary report={report} student={profile} />
          </motion.div>
        </div>

        {/* Stats row */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="mt-6 grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3"
        >
          {[
            { label: 'Strengths', value: stats.strengths, color: 'text-emerald-600 dark:text-emerald-400' },
            { label: 'Weaknesses', value: stats.weaknesses, color: 'text-amber-600 dark:text-amber-400' },
            { label: 'Missing Skills', value: stats.missing, color: 'text-rose-600 dark:text-rose-400' },
            { label: 'Companies', value: stats.companies, color: 'text-brand-600 dark:text-brand-300' },
            { label: 'Roadmap Phases', value: stats.roadmapItems, color: 'text-accent-600 dark:text-accent-300' },
            { label: 'Projects', value: stats.projects, color: 'text-brand-600 dark:text-brand-300' },
          ].map((s) => (
            <div key={s.label} className="card-surface p-4 text-center">
              <p className={`font-display text-2xl font-bold tabular-nums ${s.color}`}>{s.value}</p>
              <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{s.label}</p>
            </div>
          ))}
        </motion.div>

        {/* Best role + radar */}
        <div className="mt-6 grid gap-6 lg:grid-cols-2">
          <BestRoleCard role={report.bestRole || profile.targetRole} companies={report.recommendedCompanies} />
          <SkillRadarChart report={report} />
        </div>

        {/* Strengths + weaknesses */}
        <div className="mt-6 grid gap-6 md:grid-cols-2">
          <StrengthsCard strengths={report.strengths} />
          <WeaknessesCard weaknesses={report.weaknesses} />
        </div>

        {/* Missing skills + skill gap */}
        <div className="mt-6 grid gap-6 md:grid-cols-2">
          <MissingSkillsCard skills={report.missingSkills} />
          <SkillGapCard items={report.skillGapAnalysis} />
        </div>

        {/* Roadmap */}
        <div className="mt-6">
          <RoadmapCard roadmap={report.roadmap} />
        </div>

        {/* Projects + certifications */}
        <div className="mt-6 grid gap-6 lg:grid-cols-3">
          <div className="lg:col-span-2">
            <ProjectsCard projects={report.recommendedProjects} />
          </div>
          <CertificationsCard items={report.recommendedCertifications} />
        </div>

        {/* Tips */}
        <div className="mt-6 grid gap-6 md:grid-cols-2">
          <TipsCard title="Coding Improvement Tips" tips={report.codingTips} icon="code" accent="brand" />
          <TipsCard title="Communication Improvement Tips" tips={report.communicationTips} icon="message" accent="accent" />
        </div>

        {/* Interview questions */}
        <div className="mt-6">
          <InterviewQuestionsCard questions={report.interviewQuestions} />
        </div>

        {/* Final recommendation */}
        <div className="mt-6">
          <FinalRecommendationCard recommendation={report.finalRecommendation} />
        </div>

        {/* Bottom CTA */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="mt-10 card-surface p-6 flex flex-wrap items-center justify-between gap-4"
        >
          <div>
            <h3 className="font-display text-lg font-semibold text-slate-900 dark:text-white">Download your full report</h3>
            <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">A polished PDF you can share with mentors or keep for yourself.</p>
          </div>
          <div className="flex flex-wrap gap-2">
            <Button variant="ghost" onClick={() => navigate('/assessment')} leftIcon={<RotateCcw className="h-4 w-4" />}>Re-run assessment</Button>
            <Button onClick={handleDownload} loading={downloading} leftIcon={<Download className="h-4 w-4" />}>Download PDF</Button>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
